name: Test

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

# vim:ts=2:sw=2:et
